from sqlmodel import Field
from sqlmodel import SQLModel


class HiredEmployees(SQLModel, table=True):
    """
    hired_employees.csv:
        id INTEGER Id of the employee
        name STRING Name and surname of the employee
        datetime STRING Hire datetime in ISO format
        department_id INTEGER Id of the department which the employee was hired for
        job_id INTEGER Id of the job which the employee was hired for
    """

    # Although id is a primary_key and it is supposed not to be null,
    # in SQLModel we define it as
    #
    #   int | None  with its default value as Field(default=None, primary_key=True)
    #
    # so that whenever we create an instance of this class (in the next chapters),
    # we will not set the id, to let the id to be generated by the database,
    # not by our code (remember that the id will is required in the database).
    id: int | None = Field(default=None, primary_key=True)
    name: str
    datetime: str | None = Field(default=None)
    department_id: int | None = Field(default=None, index=True)
    job_id: int = Field(index=True)


class Departments(SQLModel, table=True):
    """
    A Table with the following columns:

        id (int): Id of the department
        department (str): Name of the department
    """

    department_id: int | None = Field(default=None, primary_key=True)
    department: str


class Jobs(SQLModel, table=True):
    """
    A Table with the following columns:

        id (int): Id of the job
        job (str): Name of the job
    """

    job_id: int | None = Field(default=None, primary_key=True)
    job: str
